CLASS zcl_acallh_test4 DEFINITION
  PUBLIC
  ABSTRACT
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES zif_acallh_test2 ABSTRACT METHODS execute.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_acallh_test4 IMPLEMENTATION.
ENDCLASS.
